graphhopper:

  # OSM file path
  datareader.file: "data/lithuania-latest.osm.pbf"

  # Graph cache location
  graph.location: data/graph-cache

  ##### Profiles ####

  profiles:
    - name: car
      custom_model_files: [car.json]
    - name: bike
      custom_model_files: [bike.json, bike_elevation.json]
    - name: foot
      custom_model_files: [foot.json, foot_elevation.json]
    - name: kayak
      custom_model_files: [kayak.json]

  # Acceleration modes
  profiles_ch:
    - profile: car
  profiles_lm: []

  #### Encoded Values ####

  graph.encoded_values: |
    kayak_access, kayak_average_speed, waterway_obstacle,
    car_access, car_average_speed, country, road_class, roundabout, max_speed, road_class_link, road_environment,
    foot_access, foot_average_speed, foot_priority, foot_road_access, hike_rating, average_slope,
    bike_access, bike_average_speed, bike_priority, bike_road_access, bike_network, mtb_rating, ferry_speed

  #### Elevation provider ####
  graph.elevation.provider: srtm

  #### Subnetworks ####

  # min_network_size helps to remove small disconnected subgraphs.
  # 200 is a safe value for car/bike/foot to avoid "island" issues.
  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1

  #### Routing ####

  routing.snap_preventions_default: tunnel, bridge, ferry
  routing.non_ch.max_waypoint_distance: 1000000

  #### Storage ####
  
  import.osm.ignored_highways: ''

  graph.dataaccess.default_type: RAM_STORE

server:
  application_context_path: /route
  application_connectors:
  - type: http
    port: 8989
    bind_host: 0.0.0.0
    max_request_header_size: 50k
  request_log:
      appenders: []
  admin_connectors:
  - type: http
    port: 8990
    bind_host: 0.0.0.0

logging:
  appenders:
    - type: file
      time_zone: UTC
      current_log_filename: logs/graphhopper.log
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      archive: true
      archived_log_filename_pattern: ./logs/graphhopper-%d.log.gz
      archived_file_count: 30
      never_block: true
    - type: console
      time_zone: UTC
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  loggers:
    "com.graphhopper.osm_warnings":
      level: DEBUG
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/osm_warnings.log
          archive: false
          logFormat: '[%level] %msg%n'
