services:
  graphhopper:
    build: .
    container_name: graphhopper-openmap
    ports:
      - "8988:8989"
    environment:
      - JAVA_OPTS=-Xmx4g -Xms4g -server
    volumes:
      - ./config-openmap.yml:/graphhopper/config.yml:ro
      - ./data:/graphhopper/data
    restart: always
